services:
  nginx:
    image: nginx:latest
    container_name: nginx-con
    ports:
      - 5959:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php:fpm
    container_name: php-con
    volumes:
      - ./php:/var/www/html/
